### listar currencyes
GET http://localhost:8080/currencyes
Content-Type: application/json

### listar quotations
GET http://localhost:8080/currencyes/1/quotations
Content-Type: application/json

### listar situação de documentos
GET http://localhost:8080/situacoes
Content-Type: application/json

### listar documentos
GET http://localhost:8080/currencyes/1/quotations/1/documentos
Content-Type: application/json

### novo documento
POST http://localhost:8080/currencyes/1/quotations/2/documentos
Content-Type: application/json

{
  "titulo": "um novo documento"
}

### atualizar documento
PUT http://localhost:8080/currencyes/1/quotations/2/documentos
Content-Type: application/json

{
  "id": 2,
  "titulo": "alterando documento"
}
